CREATE TABLE BOOK
(
    BOOK_ID        BIGINT NOT NULL AUTO_INCREMENT,
    BOOK_NAME      VARCHAR(200),
    ISBN           VARCHAR(20),
    BOOK_AUTHOR_ID BIGINT NOT NULL,
    PRICE          DECIMAL(10, 2),
    CREATE_DATE    TIMESTAMP,
    UPDATE_DATE    TIMESTAMP,
    CONSTRAINT BOOKS_PK PRIMARY KEY (BOOK_ID)
);

insert into BOOK(BOOK_NAME, ISBN, BOOK_AUTHOR_ID, CREATE_DATE)
values ('Think in Java', '9861815023', 1, NOW());

insert into BOOK(BOOK_NAME, ISBN, BOOK_AUTHOR_ID, CREATE_DATE)
values ('Think in C#', '9780130385727', 1, NOW());

insert into BOOK(BOOK_NAME, ISBN, BOOK_AUTHOR_ID, CREATE_DATE)
values ('Thinking Functionally in PHP', '453454575678', 1, NOW());

CREATE TABLE BOOK_AUTHOR
(
    BOOK_AUTHOR_ID BIGINT NOT NULL AUTO_INCREMENT,
    BOOK_ID        BIGINT NOT NULL,
    AUTHOR_ID      BIGINT NOT NULL,
    CREATE_DATE    TIMESTAMP,
    UPDATE_DATE    TIMESTAMP,
    CONSTRAINT BOOK_AUTHOR_PK PRIMARY KEY (BOOK_AUTHOR_ID)
);

insert into BOOK_AUTHOR (BOOK_ID, AUTHOR_ID, CREATE_DATE)
values (1, 1, NOW());

CREATE TABLE AUTHOR
(
    AUTHOR_ID   BIGINT NOT NULL AUTO_INCREMENT,
    AUTHOR_NAME VARCHAR(200),
    CREATE_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP,
    CONSTRAINT AUTHOR_PK PRIMARY KEY (AUTHOR_ID)
);

insert into AUTHOR (AUTHOR_NAME, CREATE_DATE)
values ('Bruce Eckel', now());
